# Stage 1: Building the app
FROM node:16-alpine as build-stage

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build:admin

# Stage 2: Serve the app with Nginx
FROM nginx:stable-alpine

COPY --from=build-stage /app/build /usr/share/nginx/html

# Copy your nginx configuration if you have any custom settings
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
