version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: medusa_user
      POSTGRES_PASSWORD: medusa_password
      POSTGRES_DB: medusa_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    volumes:
      - redis_data:/data

  medusa-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: postgresql://medusa_user:medusa_password@postgres/medusa_db
      REDIS_URL: redis://redis:6379
    command: npm run start
    depends_on:
      - postgres
      - redis

  medusa-admin:
    build:
      context: ./path/to/admin
      dockerfile: Dockerfile.admin # Adjust this path to where your Dockerfile for the admin is located
    ports:
      - "7000:80" # Assuming Nginx serves on port 80, map it to 7000 on the host
    depends_on:
      - medusa-backend

volumes:
  postgres_data:
  redis_data:
  medusa_admin_build: # This volume will be used to store the built admin panel

networks:
  coolify:
    name: coolify
    external: true


