version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: medusa_user
      POSTGRES_PASSWORD: medusa_password
      POSTGRES_DB: medusa_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    volumes:
      - redis_data:/data

  medusa-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend # Ensure you have a Dockerfile for backend setup
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: postgresql://medusa_user:medusa_password@postgres/medusa_db
      REDIS_URL: redis://redis:6379
    command: npm run start
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
