x-logging:
  logging:
    driver: json-file
    options:
      max-file: '5'
      max-size: 10m
version: '3'
services:
  appwrite:
    image: 'appwrite/appwrite:1.4'
    container_name: appwrite
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: 10m
    volumes:
      - 'appwrite-uploads:/storage/uploads:rw'
      - 'appwrite-cache:/storage/cache:rw'
      - 'appwrite-config:/storage/config:rw'
      - 'appwrite-certificates:/storage/certificates:rw'
      - 'appwrite-functions:/storage/functions:rw'
    depends_on:
      - appwrite-mariadb
      - appwrite-redis
      - appwrite-influxdb
    environment:
      - SERVICE_FQDN_APPWRITE=/
volumes:
  appwrite-mariadb: null
  appwrite-redis: null
  appwrite-cache: null
  appwrite-uploads: null
  appwrite-certificates: null
  appwrite-functions: null
  appwrite-builds: null
  appwrite-influxdb: null
  appwrite-config: null
